version: '3.8'

services:
  nginx:
    image: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: 'serverName=Docker'
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: task
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
    networks:
      - backend

volumes:
  mysql:

networks:
  backend:
